name: quran_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Features
  home:
    path: features/home
  splash:
    path: features/splash
  detail_surah:
    path: features/detail_surah
  bookmark:
    path: features/bookmark
  search:
    path: features/search
  ai_assistant:
    path: features/ai_assistant
  settings:
    path: features/settings
  library_feature:
    path: features/library

  # Domains
  quran:
    path: domains/quran
  library_domain:
    path: domains/library

  # Resources
  resources:
    path: resources/resources

  # Shared Libraries
  common:
    path: shared_libraries/common
  core:
    path: shared_libraries/core
  dependencies:
    path: shared_libraries/dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

dependency_overrides:
  win32: ^5.13.0
  isar_flutter_libs:
    path: third_party/isar_flutter_libs

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/data/
    - assets/
